package lwjgladapter.input;

public class KeyboardKeyUtil {

	public static final String convertKeyboardKeyToString(KeyboardKey key){
		switch (key) {
		case KEY_0:
			return "0";
		case KEY_1:
			return "1";
		case KEY_2:
			return "2";
		case KEY_3:
			return "3";
		case KEY_4:
			return "4";
		case KEY_5:
			return "5";
		case KEY_6:
			return "6";
		case KEY_7:
			return "7";
		case KEY_8:
			return "8";
		case KEY_9:
			return "9";
		case KEY_A:
			return "A";
		case KEY_B:
			return "B";
		case KEY_C:
			return "C";
		case KEY_D:
			return "D";
		case KEY_E:
			return "E";
		case KEY_F:
			return "F";
		case KEY_G:
			return "G";
		case KEY_H:
			return "H";
		case KEY_I:
			return "I";
		case KEY_J:
			return "J";
		case KEY_K:
			return "K";
		case KEY_L:
			return "L";
		case KEY_M:
			return "M";
		case KEY_N:
			return "N";
		case KEY_O:
			return "O";
		case KEY_P:
			return "P";
		case KEY_Q:
			return "Q";
		case KEY_R:
			return "R";
		case KEY_S:
			return "S";
		case KEY_T:
			return "T";
		case KEY_U:
			return "U";
		case KEY_V:
			return "V";
		case KEY_W:
			return "W";
		case KEY_X:
			return "X";
		case KEY_Y:
			return "Y";
		case KEY_Z:
			return "Z";
		case KEY_ALT_LEFT:
			return "ALT_LEFT";
		case KEY_ALT_RIGHT:
			return "ALT_RIGHT";
		case KEY_ARROW_DOWN:
			return "ARROW_DOWN";
		case KEY_ARROW_LEFT:
			return "ARROW_LEFT";
		case KEY_ARROW_RIGHT:
			return "ARROW_RIGHT";
		case KEY_ARROW_UP:
			return "ARROW_UP";
		case KEY_BACKSPACE:
			return "BACKSPACE";
		case KEY_CRTL_LEFT:
			return "CRTL_LEFT";
		case KEY_CRTL_RIGHT:
			return "CRTL_RIGHT";
		case KEY_ENTER:
			return "ENTER";
		case KEY_ESCAPE:
			return "ESCAPE";
		case KEY_F1:
			return "F1";
		case KEY_F10:
			return "F10";
		case KEY_F11:
			return "F11";
		case KEY_F12:
			return "F12";
		case KEY_F2:
			return "F2";
		case KEY_F3:
			return "F3";
		case KEY_F4:
			return "F4";
		case KEY_F5:
			return "F5";
		case KEY_F6:
			return "F6";
		case KEY_F7:
			return "F7";
		case KEY_F8:
			return "F8";
		case KEY_F9:
			return "F9";
		case KEY_NUM0:
			return "0";
		case KEY_NUM1:
			return "1";
		case KEY_NUM2:
			return "2";
		case KEY_NUM3:
			return "3";
		case KEY_NUM4:
			return "4";
		case KEY_NUM5:
			return "5";
		case KEY_NUM6:
			return "6";
		case KEY_NUM7:
			return "7";
		case KEY_NUM8:
			return "8";
		case KEY_NUM9:
			return "9";
		case KEY_SHIFT_LEFT:
			return "SHIFT_LEFT";
		case KEY_SHIFT_RIGHT:
			return "SHIFT_RIGHT";
		case KEY_SPACE:
			return "SPACE";
		case KEY_TAB:
			return "TAB";
		case NONE:
			return "NONE";
		}
		return "";
	}

}
