package lwjgladapter.input.gamepad;

import static org.lwjgl.glfw.GLFW.*;

public enum GamepadButton {
	XBOX_A(GLFW_GAMEPAD_BUTTON_A),
	XBOX_B(GLFW_GAMEPAD_BUTTON_B),
	XBOX_X(GLFW_GAMEPAD_BUTTON_X),
	XBOX_Y(GLFW_GAMEPAD_BUTTON_Y),
	PS_CIRCLE(GLFW_GAMEPAD_BUTTON_CIRCLE),
	PS_TRIANGLE(GLFW_GAMEPAD_BUTTON_TRIANGLE),
	PS_SQUARE(GLFW_GAMEPAD_BUTTON_SQUARE),
	PS_CROSS(GLFW_GAMEPAD_BUTTON_CROSS),
	LB(GLFW_GAMEPAD_BUTTON_LEFT_BUMPER),
	RB(GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER),
	LEFT_THUMBSTICK(GLFW_GAMEPAD_BUTTON_LEFT_THUMB),
	RIGHT_THUMBSTICK(GLFW_GAMEPAD_BUTTON_RIGHT_THUMB),
	BACK(GLFW_GAMEPAD_BUTTON_BACK),
	START(GLFW_GAMEPAD_BUTTON_START),
	GUIDE(GLFW_GAMEPAD_BUTTON_GUIDE),
	D_UP(GLFW_GAMEPAD_BUTTON_DPAD_UP),
	D_RIGHT(GLFW_GAMEPAD_BUTTON_DPAD_RIGHT),
	D_LEFT(GLFW_GAMEPAD_BUTTON_DPAD_LEFT),
	D_DOWN(GLFW_GAMEPAD_BUTTON_DPAD_DOWN);
	
	private int glfwValue;
	
	private GamepadButton(int glfwValue){
		this.glfwValue = glfwValue;
	}

	public int getGlfwValue() {
		return glfwValue;
	}
}
